# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

$num_instances = 3
$instance_name_prefix = "ddd"
$vm_gui = false
$vm_memory = 1024
$vm_cpus = 1
$forwarded_ports = {}

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = "dutchdockerday"
  config.vm.box_url = "../packer/images/dutchdockerday.box"

  config.vm.provider :virtualbox do |vb|
    vb.check_guest_additions = false
    vb.functional_vboxsf = false
  end

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "%s-%02d" % [$instance_name_prefix, i] do |config|
      config.vm.hostname = vm_name

      $forwarded_ports.each do |guest, host|
        config.vm.network "forwarded_port", guest: guest, host: host, auto_correct: true
      end

      config.vm.provider :virtualbox do |vb|
        vb.gui = $vm_gui
        vb.memory = $vm_memory
        vb.cpus = $vm_cpus
      end

      ip = "172.17.8.#{i+100}"
      config.vm.network :private_network, ip: ip

      # Copy the Nomad config files.
      config.vm.provision "shell", inline: "cp -R /vagrant/nomad/*.hcl /etc/nomad/"

      # Set the Nomad node name and ip.
      nodeip = "\"#{ip}\""
      nodename = "\"ddd-0#{i}\""
      config.vm.provision "shell" do |s|
        s.inline = "echo \"name=$1\nbind_addr=$2\" > /etc/nomad/node.hcl"
        s.args = [nodename, nodeip]
      end

      # Add the node itself to hosts
      config.vm.provision "shell", inline: "echo \"127.0.0.1    localhost\n127.0.1.1    #{vm_name}\" > /etc/hosts"

      # Add the other nodes to hosts
      (1.. $num_instances).each do |host|
        if vm_name != "ddd-0#{host}" then
          config.vm.provision "shell", inline: "echo \"172.17.8.#{host+100}    ddd-0#{host}\" >> /etc/hosts"
        end
      end
    end
  end
end
